### ISSUE TITLE
Personicle web dashboard: dashboard page information blurbs and metric summary alignment

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#185]
![Image](https://user-images.githubusercontent.com/97196207/216905313-c0fa262e-d375-4440-a23a-c0eb40e0735d.png)

**Comment by zara-clearsense** [comment]
The asymmetry between different widgets is caused by the different amount of font in each widget. "No sleep events for past week" takes up more space than "No calories data" and "No steps data". This cannot be changed, and at certain resizes for the window, one of the widgets looks noticeably smaller as the text adjusts inside the widget. But at other sizes they all become an equal size. 

It was also caused by 2 of the divs containing col-xl-4 whereas one of the divs contained col-xl-3. This has been rectified.

**Comment by zara-clearsense** [comment]
Login Page was removed in the above pull request from information-hovers-headers branch.

**Comment by vaibhav-clearsense** [comment]
Closed by https://github.com/ClearsenseData/personicle-rails/pull/197
